; Warcraft III 3.0 World Editor Windows 7 Fix
; Set the full path to World Editor.exe.
; Leave blank in the future release to use auto-detection / manual fallback.
WorldEditorPath=C:\Games\War3\Warcraft III\_retail_\x86_64\World Editor.exe
